[[redirects]]
  from = "/:year/:month/:slug"
  to = "/posts/:year/:month/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/about-me/"
  to = "/"
  status = 301
  force = true

[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"