import Header from "./components/header";
import Footer from "./components/footer";

import "./globals.css";

export const metadata = {
  title: 'Francesco Rampazzo',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
